### ISSUE TITLE
Using ⌥ in hotkeys?

### ISSUE THREAD

**Issue by 9mm** [madsmtm/menubar#5]
Hey, I'm looking to do a "Hide others" hotkey which is usually `⌥+⌘+H`

I see command looks like its already added

```
            menu.add(MenuItemWrapper::new("Hide Neovide", "h", None));
            menu.add(MenuItemWrapper::new("Hide Others", "", None));
```

Is there a way I can use this specific key?

**Comment by madsmtm** [comment]
General note on stability/readyness: I wouldn't recommend this crate to anyone yet.

I think we need to, on macOS at least, set [`keyEquivalentModifierMask`](https://developer.apple.com/documentation/appkit/nsmenuitem/1514815-keyequivalentmodifiermask?language=objc) to the desired modifiers.

This can be done if you use `icrate` directly, something like `menuitem.setKeyEquivalentModifierMask(NSEventModifierFlagOption | NSEventModifierFlagCommand)`, though that is currently unimplemented in `menubar`.

**Comment by 9mm** [comment]
Hey, thanks for letting me know. Just as a precursor to what I'm about to say, I'm new to rust (I've written 5 lines total) and I'm trying to help the Neovide project implement a native OSX menu. They use winit, and the default winit menu is preventing certain hotkeys from being captured (like `⌘-Q` quit on OSX).

So far I have disabled the default winit menu, and now I'm setting off to rebuild the menu using this crate and so far it seems to work pretty good, aside form overwriting the actual hotkey combinations.

I think for the use case of Neovide, it can be a very simple menu. Essentially I want to re-create About, Hide (`⌘-H`), Hide Others (`⌥+⌘+H`), Quit (`⌘+Q`), and a window menu with Minimize (`⌘+M`) (plus other default window hotkeys, like "Full Screen" with `⌃+⌘+F`). More could be added later.

So if you do not recommend this library (yet), can you roughly outline the steps I might take to do something like this above, [as if i were a golden retriever](https://www.youtube.com/watch?v=SmHl7hKlVj4)? I checked out `icrate` and it looks like native OSX <-> rust bindings, although I don't know objective C. I could figure it out perhaps if there were examples somewhere of using it to create a menu (like I did with the code examples for `menubar`, they were extremely helpful). Or even a point in the right direction of what crate (this, objc2, icrate, or otherwise) which might best accomplish this goal

Thank you for any help, if you feel like it, although of course no obligation. Thanks!!

**Comment by madsmtm** [comment]
If you only want macOS support, then you should use `icrate` (which is still somewhat unstable, but at least less so than this crate). If you want multiplatform support, then you probably have to write your menu code separately for each platform currently.

### Generally

I think the best code examples would probably be to find Objective-C examples on how to programmatically create and configure menus in AppKit (probably loads out there, haven't really checked).

Once you've found code to do that, you could port it to using `icrate`, once you understand how the latter works - I am in the process of [writing a tutorial on that](https://github.com/madsmtm/objc2/pull/494), but I keep getting caught up in other things.

### Concretely

`menubar` fairly precisely follows AppKit's API, e.g. `MenuItemWrapper` is basically just `NSMenuItem` with convenience functions; so I think if you check out the source code for `menubar::appkit`, and convert all your uses of `MenuItemWrapper` to `NSMenuItem` (and so on), then you'll have something functional at the end.

Another example can be found in [`winit`'s own menu code](https://github.com/rust-windowing/winit/blob/af247eac0f62fc4a1dfb025470f809d3413536d9/src/platform_impl/macos/menu.rs); that still uses manual definitions of `NSMenu` and `NSMenuItem` (because I haven't updated it yet), but I think it should be possible to convert from that to `icrate`.

I hope that helps!

**Comment by 9mm** [comment]
Cool, thank you! I appreciate it. This gives me a great direction.
